// This file is a placeholder. Replace with the file generated by:
// flutterfire configure

class DefaultFirebaseOptions {
  static dynamic get currentPlatform =>
      throw UnimplementedError('Run flutterfire configure to generate this file.');
}

